#!/usr/bin/env bash
# Verify Rememoru and build the single-file zipapp.
# Usage: scripts/build.sh [--clean]
set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
readonly REPOSITORY_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPOSITORY_ROOT"

# --clean resets generated bytecode for convention; the suite discovers anew.
if [[ "${1:-}" == "--clean" ]]; then
  find . -name '__pycache__' -type d -prune -exec rm -rf {} +
fi

echo "== offline tests"
python3 -m unittest discover -s tests

echo "== syntax check"
python3 -m compileall -q rememoru

echo "== zipapp"
mkdir -p dist
rm -f dist/rememoru.pyz
python3 -m zipapp rememoru --python '/usr/bin/env python3' -o dist/rememoru.pyz
echo "Built dist/rememoru.pyz"
